version: '2'
services:
  nginx:
    container_name: qgisserver-perfsuite-nginx
    image: nginx:1.13
    ports:
      - 8088:80
    networks:
      - qgis
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - qgis-2.14
      - qgis-2.18
      - qgis-3.0
      - qgis-3.2
      - qgis-3.0-parallel-rendering
      - qgis-master
      - qgis-master-parallel-rendering
  qgis-2.14:
    container_name: qgisserver-perfsuite-2.14
    image: qgisserver-perfsuite/2.14
    networks:
      - qgis
      - data
    volumes:
      - ./data:/data
  qgis-2.18:
    container_name: qgisserver-perfsuite-2.18
    image: qgisserver-perfsuite/2.18
    networks:
      - qgis
      - data
    volumes:
      - ./data:/data
  qgis-3.0:
    container_name: qgisserver-perfsuite-3.0
    image: qgisserver-perfsuite/3.0
    networks:
      - qgis
      - data
    volumes:
      - ./data:/data
    environment:
      - QGIS_SERVER_PARALLEL_RENDERING=0
  qgis-3.0-parallel-rendering:
    container_name: qgisserver-perfsuite-3.0-parallel-rendering
    image: qgisserver-perfsuite/3.0
    networks:
      - qgis
      - data
    volumes:
      - ./data:/data
    environment:
      - QGIS_SERVER_PARALLEL_RENDERING=1
      - QGIS_SERVER_MAX_THREADS=4
  qgis-3.2:
    container_name: qgisserver-perfsuite-3.2
    image: qgisserver-perfsuite/3.2
    networks:
      - qgis
      - data
    volumes:
      - ./data:/data
    environment:
      - QGIS_SERVER_PARALLEL_RENDERING=0
  qgis-3.2-parallel-rendering:
    container_name: qgisserver-perfsuite-3.2-parallel-rendering
    image: qgisserver-perfsuite/3.2
    networks:
      - qgis
      - data
    volumes:
      - ./data:/data
    environment:
      - QGIS_SERVER_PARALLEL_RENDERING=1
      - QGIS_SERVER_MAX_THREADS=4
  qgis-master:
    container_name: qgisserver-perfsuite-master
    image: qgisserver-perfsuite/master
    networks:
      - qgis
      - data
    volumes:
      - ./data:/data
    environment:
      - QGIS_SERVER_PARALLEL_RENDERING=0
  qgis-master-parallel-rendering:
    container_name: qgisserver-perfsuite-master-parallel-rendering
    image: qgisserver-perfsuite/master
    networks:
      - qgis
      - data
    volumes:
      - ./data:/data
    environment:
      - QGIS_SERVER_PARALLEL_RENDERING=1
      - QGIS_SERVER_MAX_THREADS=4
  data:
    container_name: qgisserver-perfsuite-data
    image: qgisserver-perfsuite/data
    networks:
      - data

networks:
  data:
    driver: bridge
  qgis:
    driver: bridge
